name: CI

on: ['push', 'pull_request']

jobs:
        ci:
                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v2 
                        - name: git
                          run: mkdir temp && cd temp && git init
                        - name: libgit2
                          run: sudo apt-get install -y libgit2-dev
                        - name: cmake
                          run: mkdir build && cd build && cmake ..
                        - name: build
                          run: cmake --build build 
                        - name: test
                          run: cd build && ctest
